### ISSUE TITLE
Generate a user friendly string for gender

### ISSUE THREAD

**Issue by smacgregor** [TeamCritterFinder/CritterFinder#40]
Currently our UI shows "M" or "F" for animal gender. These aren't very user friendly. Ideally we'd show "Male" or "Female".

Maybe we can add a helper method in our helpers package that will convert our Gender enumerated type into one of the string values we get from:

```
<string-array name="gender">
    <item>Male</item>
    <item>Female</item>
    <item>Both</item>
</string-array>
```

i.e. convertGenderToString(SearchFilter.Gender gender) {
   // lookup the gender in the string-array in our resources folder and return that value
}

**Comment by scottrichards** [comment]
How about a Male Female Sign instead of the name "Male" "Female" spelled out?

**Comment by scottrichards** [comment]
I created a Pull Request for this task

**Comment by smacgregor** [comment]
Scott fixed this.
