### ISSUE TITLE
Information design for the pet details screen

### ISSUE THREAD

**Issue by smacgregor** [TeamCritterFinder/CritterFinder#44]
What pet attributes do we want to see on the pet details fragment? Add them.

**Comment by cbaja** [comment]
Informations design need for pet details screen
- Sex 
- Size
- Age
- Breed
- Shelter Information ( Adress,Phone,Contact,email)

Functionality we can add to improve 
- Share the dog information we selected to others via email or Facebook
- Contact the shelter by email or by telephone

@smacgregor @scottrichards

**Comment by smacgregor** [comment]
Agreed - all this information should be on the details screen!
