### ISSUE TITLE
Expose multiple pet photos on the pet model

### ISSUE THREAD

**Issue by smacgregor** [TeamCritterFinder/CritterFinder#49]
If a pet has more than one photo we want to expose that so we can load it from the details screen.

**Comment by scottrichards** [comment]
Looks like this is already working.  Awesome!

**Comment by smacgregor** [comment]
@scottrichards - this isn't working yet. Our pet models aren't exposing an array of image urls which is what this ticket is tracking.

I owned a ticket for building the UI which is currently wired to mock data. Once you add this I'll udpdate the view to use the real stuff! Woo Hoo.

**Comment by smacgregor** [comment]
Scott checked this in and its working great.
