### ISSUE TITLE
Clicking on Search Menu button should dismiss the search filter activity and perform the search

### ISSUE THREAD

**Issue by smacgregor** [TeamCritterFinder/CritterFinder#63]

**Comment by scottrichards** [comment]
Added this in the cosmetic_improvements branch

**Comment by scottrichards** [comment]
FYI I fixed this issue, re-assigned to myself and closed it out.

**Comment by smacgregor** [comment]
Scott I had merged the cosmetic_improvements branch last night after class. So you'll need to open a new PR up from cosmetic_improvements to master so we can get this on master. 

Thanks for doing it!

**Comment by smacgregor** [comment]
Scott just pushed this to master earlier today. Thanks Scott! Closing out.
