### ISSUE TITLE
Favorites View : Remove Horizontal Divider

### ISSUE THREAD

**Issue by scottrichards** [TeamCritterFinder/CritterFinder#86]
Do we want to remove the horizontal divider?  Or does it help separate the items.

**Comment by smacgregor** [comment]
@scottrichards @cbaja 

Here's what it looks like without the divider. What do you guys think? Keep 'em or lose them?

![divider](https://cloud.githubusercontent.com/assets/1521460/13910286/86e90f5a-eedc-11e5-9bc1-1aecab963992.gif)

**Comment by smacgregor** [comment]
if we remove them I'd add a little more vertical padding between the rows so the images aren't so close together
